NAME = libft.a

SRC = ft_atoi.c \
	  ft_bzero.c \
	  ft_isalnum.c \
	  ft_isalpha.c \
	  ft_isdigit.c \
	  ft_memchr.c \
	  ft_memcmp.c \
	  ft_memcpy.c \
	  ft_memmove.c \
	  ft_memset.c \
	  ft_strchr.c \
	  ft_strlcat.c \
	  ft_strlcpy.c \
	  ft_strlen.c \
	  ft_strcmp.c \
	  ft_strncmp.c \
	  ft_strnstr.c \
	  ft_strrchr.c \
	  ft_tolower.c \
	  ft_toupper.c \
	  ft_isascii.c \
	  ft_isprint.c \
	  ft_calloc.c \
	  ft_strdup.c \
	  ft_substr.c \
	  ft_strjoin.c \
	  ft_strtrim.c \
	  ft_split.c \
	  ft_itoa.c \
	  ft_strmapi.c \
	  ft_striteri.c \
	  ft_putchar_fd.c \
	  ft_putstr_fd.c \
	  ft_putendl_fd.c \
	  ft_putnbr_fd.c \
	  get_next_line.c \
	  ft_flags_utils.c \
	  ft_print_utils.c \
	  ft_printf.c \
	  ft_ptr_utils.c \
	  ft_size_utils.c

BONUS = ft_lstnew_bonus.c \
		ft_lstadd_front_bonus.c \
		ft_lstsize_bonus.c \
		ft_lstlast_bonus.c \
		ft_lstadd_back_bonus.c \
		ft_lstdelone_bonus.c \
		ft_lstclear_bonus.c \
		ft_lstiter_bonus.c \
		ft_lstmap_bonus.c

OBJ = $(SRC:.c=.o)

OBJS = ${OBJ} ${BONUS:.c=.o}

HEAD = libft.h

AR = ar -rcs

CC = cc

FLAGS = -Wall -Werror -Wextra

all: ${NAME}

$(NAME): ${OBJ}
	@${AR} ${NAME} ${OBJ}

.c.o:
	@${CC} -o $@ -c $< ${FLAGS}

clean:
	@rm -f ${OBJS}

bonus: ${OBJS}
	@${AR} ${NAME} ${OBJS}

fclean: clean
	@rm -f ${NAME}

re: fclean all

.PHONY: clean flcean re all
